name: Question
description: Ask a question about busylight_core
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        **Ask a question about busylight_core**

  - type: textarea
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true

  - type: input
    attributes:
      label: Platform
      description: What operating system and architecture are you using? (see `uname -orsm`)
      placeholder: e.g., macOS 14 arm64, Windows 11 x86_64, Ubuntu 20.04 amd64
    validations:
      required: false

  - type: input
    attributes:
      label: Version
      description: What version of busylight_core are you using? (see `busylight_core self version`)
      placeholder: e.g., busylight_core 0.1.0
    validations:
      required: false
